[functions]
directory = "api"
included_files = ["src/shop/sammi-extensions/**.json", "src/patrons.json"]
[[redirects]]
from = "/api/*"
to = "/.netlify/functions/:splat"
status = 200
[[headers]]
  for = "/*" # you can configure the correct paths here
  [headers.values]
    access-control-allow-origin = "*"